### PR TITLE
Update mcr.cpp

### PR DESCRIPTION
**Pull request by trevorwong30-c**
Hi Teammates, please kindly review the following changes we have discussed

1. Code Improvement (line 64, 68): Change ‘X’ ‘O’ to variable defined in line 38, line 40 … 
2. Bug – Syntax Error (Line 54): “Else” should be lowercase 
3. Bug – Missing namespace (Line 1): Add using namespace std; #include <iostream> 
4. Code Improvement (line 58): Change “Which cell to mark?” to more precise hints (e.g. enter the row number you want to mark, enter the col number you want to mark)

### CODE REVIEW

**Comment by zjq-hub** [comment]
yep, we need more precise introduction to the input format!

**Review by starkooo — COMMENTED** [review]
The isWin() function is a litte complex. Maybe it can be simplified.

**Review by starkooo — COMMENTED** [review]
The hint of the input should be more clear. Otherwise, the users may make some input mistakes.

**Comment by trevorwong30-c** [comment]
> The hint of the input should be more clear. Otherwise, the users may make some input mistakes.

done!

**Comment by trevorwong30-c** [comment]
> yep, we need more precise introduction to the input format!

done!

**Comment by zhaohan065413** [comment]
The naming of variables in this code can be more standardized

**Review by zhaohan065413 — COMMENTED** [review]
The naming of variables in this code can be more standardized

**Pull request merged**
